강의 리스트 스타일 선택 버튼 관련 의논 사항 반영 및 이슈 해결
Ark-inflearn/inflearn-clone-front pull request #90
Opened 2021-10-11 07:09 UTC by hyoni0817

## 의논 사항 반영

- 별점 크기를 반응형 웹에 맞게 조절
  - props로 `responsive`를 추가해줘야 반응형으로 동작하고 `reponsive`를 추가해주지 않으면 고정된 크기로 동작합니다.
  - 참고로 `responsive` 만 적는 것과 `responsive={true}`는 같은 역할을 합니다.
    - 반응형 웹에 맞게 별점크기를 변경하려 할 때
      ```jsx
      <RatingStar rating={rating} size="1.5rem" responsive />
      ``` 
    - 고정된 별점 크기를 나타내려 할 때
      ```jsx
      <RatingStar rating={rating} size="1.5rem" />
      ```

- LectureCard.tsx에서 가격을 나타내는 부분을 LecturePrice 컴포넌트로 수정

- LectureCard와 HorizonLectureCard에서 동시에 사용할 수 있게 IconButtons 컴포넌트로 수정
  - view props에 전달하는 값에 따라 강의 리스트 스타일에 맞는 아이콘 버튼을 보여줄 수 있도록 했습니다.
    ```
    <IconButtons view="Grid" />
    ```
    - props 설명

      |props|역할                              |전달하는 값                                     |
      |-----|----------------------------------|-----------------------------------------------|
      |view |강의 리스트 스타일 값을 전달하는 부분|<p>Grid: Grid 스타일</p><p>List: List 스타일</p>|

## 이슈 해결
 
- 강의 페이지에서 Grid나 List 버튼을 클릭한 후 데이터를 불러올 때 기존 화면 위에 스피너 불러오기
  - 이미 선택된 버튼을 눌렀을 경우에는 데이터 재요청을 하지 않도록 했습니다.
  - 그리고 버튼을 누르자마자 스피너가 실행되어서 기존에 화면 전환 시간이 오래 걸리는 단점도 함께 보완됐습니다.

- /courses?view=Grid -> /courses?view=List 누르고 뒤로가기 버튼을 누르면 이전 페이지로 이동하지 않고 /courses?view=List -> /courses?view=Gird 이후에 이전 페이지로 이동하는 문제를 해결
  - 기존 router.push를 사용하면 url이 변경 될 때 마다 History(브라우저 세션 기록) Stack에 쌓이게 되어 '뒤로가기'를 눌렀을 때 view가 변경된 내역이 다 반영됐습니다. 
  - router.replace를 사용했을 경우 url은 변경되지만 History stack에는 반영되지 않아서 뒤로가기를 눌렀을 때, 강의 페이지에 접근하기 전의 페이지로 바로 이동합니다. 
  
- selected-list-view 부분의 css 코드를 GlobalStyle.css가 아닌 selected-list-view을 사용하고 있는 내부 컴포넌트에 css 코드를 작성
  - getSelectedStyle 함수에 기존 selected-list-view css 코드를 저장하여, 버튼이 선택되었을 때 함수를 호출하여 데이터를 불러오게 했습니다.
    ```
    const getSelectedStyle = () => `
      background: #1dc078 !important;
      border-color: transparent !important;
      color: white;

      &:hover {
        background: #1bb571 !important;
        border-color: transparent !important;
        color: white;
      }
    `;

    const ListViewBtn = styled.button<ListViewProps>`
      ${(props) => (props.isSelected ? getSelectedStyle() : '')}
      ...
    `;
    ```
  - 참고로 `` const selected style = `background: #1dc078;...`; `` 이렇게 상수로 css 코드를 선언할 수도 있었지만 기존 styled-components 코드와 헷갈릴 수 있다고 생각하여 함수로 선언했습니다.  

## 앞으로 진행할 작업

- 각 조건 선택 버튼 부분을 컴포넌트로 분리할 때, 쿼리스트링 전달 문제에 대해 고민한 후 강의 리스트 스타일 선택 버튼을 따로 컴포넌트 분리하기
- 브라우저 너비에 따라 변경되는 별점 크기에 맞추어 등록된 리뷰수 글자 나타내는 부분도 크기 조절하기
- 정렬순 버튼 구현하기

2021-10-11 10:37 UTC, TaehwanGo commented on src/pages/courses/index.tsx
> +        dispatch({ type: LOAD_ALL_LECTURES_REQUEST });
이건 굳이 로딩스피너 때문에 리스트를 서버에서 다시 가져올 필요는 없을 것 같아요 🙂
아니면 리덕스에서 캐싱이 돼서 다시 서버 까지 안가고 바로 스토어에 있는 것을 가져오는지는 잘 모르겠네요

2021-10-11 10:49 UTC, TaehwanGo commented on src/pages/courses/index.tsx
> +      router.replace({
뒤로가기 문제를 이렇게 해결한 push에서 replace로 바꿔서 해결하셨군요 ! 👍

2021-10-11 10:51 UTC, TaehwanGo commented on src/pages/courses/index.tsx
> +    (value: string) => {
아래 if (queryView !== value) {
// ...
}
코드가 같은 버튼을 다시 클릭했을 때 중복 실행을 방지하는 것이라면
아래와 작성된 방법보단
함수 제일 처음 시작인 이 부분에 
if (queryView === value) {
  return;
}
을 추가하는 것이 좋을 것 같아요
지난번에 말씀드렸던 early return 입니다 😊

2021-10-11 11:38 UTC, TaehwanGo requested changes

2021-10-11 11:38 UTC, TaehwanGo commented on src/components/lectureCard/HorizonLectureCard.tsx
> +}))<HashTagProps>`
클래스가 어떤것을 의미하나요? 😮
CSS 클래스를 사용하는 것 같진 않은 것 같아서요

2021-10-11 11:39 UTC, TaehwanGo approved these changes

2021-10-11 11:39 UTC, TaehwanGo commented on src/components/lectureCard/HorizonLectureCard.tsx
> +}))<HashTagProps>`
클래스가 어떤것을 의미하나요? 😮
CSS 클래스를 사용하는 것 같진 않은 것 같아서요

2021-10-11 11:44 UTC, TaehwanGo commented on src/components/lectureCard/HorizonLectureCard.tsx
> +}))<HashTagProps>`
getRandomColor 를 useCallback을 사용해서 해결할 수 도 있나요?

2021-10-11 12:19 UTC, hyoni0817 commented on src/components/lectureCard/HorizonLectureCard.tsx
> +}))<HashTagProps>`
네 맞아요 :) 자동으로 적용되는 랜덤한 글자로 생성되는 class입니다. attrs 코드 적용 전후의 class name을 비교해봤는데
적용 전에는 아래 빨간 박스에서 볼 수 있듯이 클래스 명이 다 다르게 생성되었고
![랜덤 색상 함수 클래스 다른 것](https://user-images.githubusercontent.com/8364940/136788483-757d3b1a-3fba-4c1d-926c-b4f6ad2e264d.png)

attrs 적용 후에는 클래스 명이 다 같게 생성되었어요 ;)
![랜덤 색상 함수 클래스 같은 것](https://user-images.githubusercontent.com/8364940/136788749-7116d025-9ed3-4c8f-82d2-7596c3c72ab6.png)

2021-10-11 12:28 UTC, hyoni0817 commented on src/components/lectureCard/HorizonLectureCard.tsx
> +}))<HashTagProps>`
그리고 attrs을 사용하지않고, useCallback은 아래 코드로 테스트 해봤는데 
```javascript
  const getRandomColor = useCallback(() => {
    const h = 360 * Math.random();
    const s = 25 + 70 * Math.random();
    const l = 85 + 10 * Math.random();

    return `hsl(${h} ,${s}%, ${l}%)`;
  }, []);
```
console창에 경고는 발생하지 않지만 클래스 이름은 다 새로 생성되었어요. 그래서 경고와 상관없이 클래스를 새로 생성하기 위해 매번 스타일 문장 계산을 새로 하는게 좋지않은 것 같아서 attrs는 유지하되, useCallback도 함께 추가하면 좋을 것 같다는 생각이 들어요. useCallback으로 경고가 사라지는 것을 보니 개인적인 생각으로는 클래스가 새로 생성되면서 생기는 성능 문제에 대해서 최적화 시켜주는 것 같아서요😃 

좋은 의견 주셔서 감사합니다!👍😊

2021-10-11 17:59 UTC, hyoni0817 commented on src/pages/courses/index.tsx
> +    (value: string) => {
코드가 훨씬 좋아졌어요 :) 저번에 알려주신 early return을 이렇게 활용할 생각을 못했네요😅
좋은 의견 주셔서 감사합니다😊

2021-10-11 19:52 UTC, merged

2021-10-12 00:51 UTC, TaehwanGo commented on src/pages/courses/index.tsx
> +        dispatch({ type: LOAD_ALL_LECTURES_REQUEST });
저도 리덕스 툴킷은 사용안해봤는데 graqhql과 이폴로클라이언트에선 로컬 스토어에 서버로 요청하려는 데이터가 있으면 서버까지 가지 않고 로컬에서 바로 반환하더라구요
노아님이 사용하셨던 리액트쿼리도 비슷한 기능이 있는 것 같아요
그런데 리덕스에서도 그게 지원이 되는지는 잘 모르겠네요 
일단 확실하진 않으니 알아보기 전까진 주석처리 하는 것도 좋을 것 같아요 :)